tests/test_checkout.py::checkout_Test::test_checkout_successful
--------------------------------------------------------------------
Last Page: [WARNING! Browser Not Open!]
 Duration: 7.28s
  Browser: Firefox 109.0.1 / headless
   Driver: geckodriver 0.32.0
Timestamp: 1675402183  (Unix Timestamp)
     Date: Friday, 3 February 2023
     Time: 5:29:43 AM  (UTC, UTC+00)
--------------------------------------------------------------------
Traceback: File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/runner/work/pfd_proj/pfd_proj/tests/test_checkout.py", line 93, in test_checkout_successful
    self.save_screenshot_to_logs()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/seleniumbase/fixtures/base_case.py", line 3611, in save_screenshot_to_logs
    return page_actions.save_screenshot(self.driver, name, test_logpath)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/seleniumbase/fixtures/page_actions.py", line 1095, in save_screenshot
    driver.get_screenshot_as_file(screenshot_path)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 927, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 963, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 975, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
Exception: Message: Tried to run command without establishing a connection
